### ISSUE TITLE
Antes do prazo

### ISSUE THREAD

**Issue by heynemann** [ikkebr/hackinpoa#1]
@ikkebr por favor não comece a codificar antes do início do evento. ;)

O que está aqui é só boilerplate do django, sem problemas. Mas não continue evoluindo, por favor. Não seria justo com os outros times e acho que é muito mais legal fazer junto com seu time!

De qualquer forma fico muito feliz do interesse que você está demonstrando! Nos vemos lá!

**Comment by ikkebr** [comment]
Ok, é o mesmo boilerplate daqui https://github.com/ikkebr/django-esqueleto-bs (04/2014) só com as frescuras pra deploy no tsuru, coverage e travis. E como não tinha nada nas regras quanto a isso...
